### PR TITLE
adding group counts

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by pjaudiomv** [comment]
It feel like the pound sign is unneeded. It clutters things and is implied. What you think.

**Comment by radius314** [comment]
Which pound sign?

**Comment by pjaudiomv** [comment]
the hash tag prefixing the service body type

**Comment by radius314** [comment]
ok fixed

**Comment by pjaudiomv** [comment]
sweet I like it, looks good to me.

**Pull request merged**
