### PR TITLE
Sort #22

### PR DESCRIPTION
**Pull request by pjaudiomv**
I think this should do it for #22

### CODE REVIEW

**Comment by pjaudiomv** [comment]
just tested this does work fine except for the virtual roots they stay at the bottom

**Comment by pjaudiomv** [comment]
I am confused by this, the virtual roots is loading last, so the table sort has been set by time the virtual roots gets rendered in the table. I can't figure out how to wait for it to get loaded then sort.

**Comment by pjaudiomv** [comment]
Tablesorter does have a refresh method that supports sorting when new data has been added.

**Comment by radius314** [comment]
Are you stuck?

**Comment by pjaudiomv** [comment]
yup im stuck. :(

**Comment by radius314** [comment]
Ok taking a look now.

**Comment by radius314** [comment]
see #24

**Comment by pjaudiomv** [comment]
closing this in support of #24

**Pull request closed without merging**
